// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	MY_KV: KVNamespace;
	BASE_URL: string;
	AUTH_URL: string;
	AUTH_SECRET: string;
	AUTH_GOOGLE_ID: string;
	AUTH_GOOGLE_SECRET: string;
	AUTH_GITHUB_ID: string;
	AUTH_GITHUB_SECRET: string;
	MY_BUCKET: R2Bucket;
	DATABASE: D1Database;
}
