name = "proyecto-ingesoft-admin"
compatibility_date = "2024-12-04"
compatibility_flags = [ "nodejs_compat_v2" ]
pages_build_output_dir = ".vercel/output/static"

[placement]
mode = "smart"

[[d1_databases]]
binding = "DATABASE"
database_name = "proyecto-ingesoft"
database_id = "051b9fb7-888d-45cd-8efe-ec05c1df0bc3"

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "my-bucket"

[[kv_namespaces]]
binding = "MY_KV"
id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
